### ISSUE TITLE
It is possible to use this package with webpack?

### ISSUE THREAD

**Issue by ClaudioNunes** [dfrencham/ms-signalr-client#14]

**Comment by gregveres** [comment]
HI @ClaudioNunes 

I don't know the definitive answer, but I just tried it today and I am getting $.hubConnection is not a function. So I am assuming that means it is not a module and therefore can't be loaded with a module loader like webpack. 

Yea, I just looked at the source and it is not wrapped in any sort of module header. So its off to find another npm package. 

Given that it has been a couple months since you asked the question, did you find another npm signalR package to use that is usable with webpack?

**Comment by dfrencham** [comment]
Sorry for the late reply. This package is simply the official Microsoft Signal-R package, with minimal changes for npm packaging.

It may be possible to use it with webpack as discussed here: https://stackoverflow.com/questions/40030002/how-to-load-signalr-js-in-webpack-inside-angular-2

**Comment by gregveres** [comment]
Thanks. I picked signalr-amd because it has the amd wrapper and can be used directly without any additional config changes. I did see that SO answer and decided to go the amd route.
